CMD_PORT: int = 29001
RTD_PORT: int = 29000
WRIST_RS_485_PORT: int = 42000
REALTIME_API_PORT: int = 43000
IMPULSE_PORT: int = 24000
IMPULSE_ENV_VAR: str = "IMPULSE_COMPAT_MODE"
IMPULSE_IP: str = "127.0.0.1"

# IO constants
CTRLR_MAX_DIG_IN_BYTES = 8
CTRLR_MAX_AN_IN = 4
CTRLR_MAX_DIG_OUT_BYTES = 8
CTRLR_MAX_AN_OUT = 4

AVAILABLE_AN_IN_INDEX_COUNT = 4
AVAILABLE_AN_OUT_INDEX_COUNT = 4
AVAILABLE_DIG_IN_INDEX_COUNT = 24  # real count
AVAILABLE_DIG_OUT_INDEX_COUNT = 24  # real count
DIG_IN_INDEX_RANGE = range(24)
DIG_SAFETY_IN_INDEX_RANGE = range(24, 32)
JNT_CONFIRM_POS_THRESHOLD = 15  # deg

BYTE_SIZE = 8

# value according to robot core logics (btw, real amount is 24 in
# [1.2.50.33555456/3] api version)
DIGITAL_IO_INDEX_COUNT = 64

# Log constants
LOGGER_NAME = "RC_LOGGER"

# Different constants
CHECK_FREQUENCY_SEC = 0.002
CTRLR_CMD_PAYLOAD_LENGTH_SIZE = 4
CTRLR_CMD_TYPE_LENGTH = 4
FKINE_SOLUTIONS_COUNT = 8
EMPTY_BYTES = b""
IK_N_SOL = 8
JOINTS_COUNT = 6
JOYSTICK_ACCEL_MAX_DEG_SEC = 40
JOYSTICK_ACCEL_MAX_RAD_SEC = 10
JOYSTICK_SPEED_MAX_DEG_SEC = 30
JOYSTICK_SPEED_MAX_RAD_SEC = 0.5
MOVE_TO_HOME_POSE_ACCEL = 0.149066
MOVE_TO_HOME_POSE_SPEED = 0.223599
NO_FUNC_ANSWER_VALUE = 0
PREVIOUS_FKINE_SOLUTION_OFFSET = 7
RESPONSE_CODE_OFFSET = 1
SET_CTRLR_STATE_AWAIT_SEC = 60
SET_MOTION_MODE_AWAIT_SEC = 5
SET_WRIST_MODE_AWAIT_SEC = 60
WP_ADD_TIMEOUT = 5
BUFFER_CHECK_TIMEOUT = 0.2  # sec
WP_COUNTER_MAX_VALUE = 65535
PADDING_RES1_LENGTH = 7
PADDING_RES2_LENGTH = 2
WRIST_ACCEL = 3
WRIST_GYRO = 3

# Range of positions and orientations in kinematic_state
FKINE_IKINE_RESPONSE_JOINT_POSITION_SLICE = slice(1, 7)
ORIENTATION_SLICE = slice(3, 6)
POSITION_SLICE = slice(0, 3)

# Validate values
SPEED_LIMITS = (0, 3)  # м/с
ACCEL_LIMITS = (0, 15)  # м/c^2
BLEND_LIMITS = (0, None)  # м
WP_COUNT_LIMITS = (0, None)

GRAVITY_VECTOR_COUNT = 3
TCP_POSITION_COUNT = 3
POSITION_ORIENTATION_LENGTH = 6


# PACK/UNPACK FORMATS
OMM_ENABLE_DISABLE_PACK_FORMAT = "B"
CTRLR_CMD_DATA_PACK_UNPACK_FORMAT = "i"


# GUI
ALLOWED_GUI_ENTRY_SYMBOLS = r"^-?\d*\.?\d*$"

ADD_WAY_POINT_ERROR_DESCRIPTION = {
    -1: "Advanced motion algorithms are not available",
    0: "Waypoint successfully added",
    1: "Waypoint can not be added because of full buffer",
    2: "Waypoint can not be reached with current limits",
    3: "Waypoint can not be reached by current robot",
    4: "Waypoint has some non-finite values",
    5: "Can not reach desired waypoint because of singularity",
}

# Wrist constants
WRIST_MAX_DIG_OUT_BYTES = 1
WRIST_MAX_DIG_OUT = WRIST_MAX_DIG_OUT_BYTES * BYTE_SIZE

WRIST_MAX_DIG_IN_BYTES = 1
WRIST_MAX_DIG_IN = WRIST_MAX_DIG_IN_BYTES * BYTE_SIZE

REAL_WRIST_MAX_AN_IN = 2  # real count
REAL_WRIST_MAX_DIG_OUT = 2  # real count

AMPERAGE_VALUES_RANGE = (4, 20)  # мА
VOLTAGE_VALUES_RANGE = (0, 10)  # В
